config/routes.rb
Rails.application.routes.draw do
  get 'players/index'
  root 'players#index'

  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @player = PLayer.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to @player
    else
      render 'edit'
    end
  end

  def new
    #code
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player
    else
      render 'new'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to players_path
  end

  private
    def player_params
      params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_with(model: @player, local: true) do |form| %>
  <p>
    <%= form.label :nickname %><br>
    <%= form.text_field :nickname %>
  </p>

  <p>
    <%= form.label :rank %><br>
    <%= form.text_field :rank %>
  </p>

  <p>
    <%= form.label :charisma %><br>
    <%= form.text_field :charisma %>
  </p>

  <p>
    <%= form.label :wisdom %><br>
    <%= form.text_field :wisdom %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<%= link_to "Add new player", new_player_url %>
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @players.each do |player| %>
    <tr>
      <td><%= player.nickname %></td>
      <td><%= player.rank %></td>
      <td><%= player.charisma %></td>
      <td><%= player.wisdom %></td>
      <td><%= link_to 'Show', player_path(player) %></td>
      <td><%= link_to 'Edit', edit_player_path(player) %></td>
      <td><%= link_to 'Destroy', player_path(player),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/players/new.html.erb
<%= form_with scope: :player, url: players_path, local: true do |form| %>
  <p>
    <%= form.label :nickname %><br>
    <%= form.text_field :nickname %>
  </p>

  <p>
    <%= form.label :rank %><br>
    <%= form.text_field :rank %>
  </p>

  <p>
    <%= form.label :charisma %><br>
    <%= form.text_field :charisma %>
  </p>

  <p>
    <%= form.label :wisdom %><br>
    <%= form.text_field :wisdom %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p>
  <strong>Nickname:</strong>
  <%= @player.nickname %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @player.rank %>
</p>

<p>
  <strong>Charisma:</strong>
  <%= @player.charisma %>
</p>

<p>
  <strong>Wisdom:</strong>
  <%= @player.wisdom %>
</p>
<%= link_to 'Edit', edit_player_path(@player) %>
<%= link_to 'Back', players_path %>